-- Clomar Store Pro Free - Supabase schema inicial
-- Ejecutar en Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  category text default 'General',
  price numeric(12,2) default 0,
  cost numeric(12,2) default 0,
  stock numeric(12,2) default 0,
  stock_min numeric(12,2) default 2,
  image_url text default '',
  status text default 'Activo',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text default '',
  document text default '',
  address text default '',
  credit_limit numeric(12,2) default 0,
  status text default 'Activo',
  created_at timestamptz default now()
);

create table if not exists sales (
  id uuid primary key default gen_random_uuid(),
  receipt_number bigint generated by default as identity,
  customer_name text default 'Cliente',
  payment_method text default 'Efectivo',
  total numeric(12,2) default 0,
  status text default 'Pagado',
  seller_email text default auth.email(),
  created_at timestamptz default now()
);

create table if not exists sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid references sales(id) on delete cascade,
  product_id uuid references products(id),
  product_name text not null,
  qty numeric(12,2) default 1,
  price numeric(12,2) default 0,
  subtotal numeric(12,2) default 0,
  created_at timestamptz default now()
);

create table if not exists cash_movements (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  payment_method text default 'Efectivo',
  amount numeric(12,2) default 0,
  note text default '',
  created_at timestamptz default now(),
  user_email text default auth.email()
);

create table if not exists stock_movements (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references products(id),
  type text not null,
  qty numeric(12,2) default 0,
  note text default '',
  created_at timestamptz default now(),
  user_email text default auth.email()
);

alter table products enable row level security;
alter table customers enable row level security;
alter table sales enable row level security;
alter table sale_items enable row level security;
alter table cash_movements enable row level security;
alter table stock_movements enable row level security;

do $$ begin
  create policy "authenticated products" on products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated customers" on customers for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated sales" on sales for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated sale_items" on sale_items for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated cash" on cash_movements for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated stock" on stock_movements for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
exception when duplicate_object then null; end $$;

insert into products (code, name, category, price, cost, stock, stock_min) values
('0001', 'Zapatillas deportivas Newton Nimble Leather', 'Calzado', 380, 220, 5, 2),
('0002', 'Sombrero para el sol Bora Bora Booney', 'Accesorios', 80, 40, 2, 2),
('0003', 'Camisa de popelina de manga larga para hombre', 'Ropa', 120, 55, 1, 2)
on conflict (code) do nothing;
